package database

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"sync"
	"testing"
	"time"

	"github.com/nightio/pg-pull/internal/config"
	"github.com/nightio/pg-pull/internal/dump"
	"github.com/nightio/pg-pull/internal/testpostgres"
	"github.com/jackc/pgx/v5"
)

func TestCopyRoundTripAndRollback(t *testing.T) {
	if os.Getenv("PG_PULL_INTEGRATION") == "" {
		t.Skip("set PG_PULL_INTEGRATION=1 to run PostgreSQL integration tests")
	}
	ctx := context.Background()
	sourceDSN := testpostgres.DSN(t, "PG_PULL_TEST_SOURCE_DSN", "postgres:15-alpine")
	targetDSN := testpostgres.DSN(t, "PG_PULL_TEST_TARGET_DSN", "postgres:18-alpine")
	sourceAdmin := connectTestDB(t, ctx, sourceDSN)
	defer sourceAdmin.Close(ctx)
	targetAdmin := connectTestDB(t, ctx, targetDSN)
	defer targetAdmin.Close(ctx)

	execStatements(t, ctx, sourceAdmin,
		`DROP SCHEMA IF EXISTS source_data CASCADE`,
		`CREATE SCHEMA source_data`,
		`CREATE TYPE source_data.item_status AS ENUM ('new', 'ready')`,
		`CREATE SEQUENCE source_data.items_id_seq`,
		`CREATE SEQUENCE source_data.children_id_seq`,
		`CREATE TABLE source_data.items (
            id bigint PRIMARY KEY DEFAULT nextval('source_data.items_id_seq'),
            name text NOT NULL,
            payload jsonb,
            raw bytea,
            tags text[],
            identifier uuid,
            amount numeric(20,4),
            duration interval,
            status source_data.item_status,
            created_at timestamptz,
            display text GENERATED ALWAYS AS (name || ':' || id::text) STORED
        )`,
		`CREATE TABLE source_data.children (
            id bigint PRIMARY KEY DEFAULT nextval('source_data.children_id_seq'),
            item_id bigint NOT NULL REFERENCES source_data.items(id),
            note text NOT NULL
        )`,
		`CREATE INDEX items_name_idx ON source_data.items (name)`,
		`CREATE TABLE source_data.identity_items (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 2) PRIMARY KEY, note text)`,
		`INSERT INTO source_data.identity_items (note) VALUES ('identity row')`,
		`CREATE DOMAIN source_data.positive_amount AS numeric(20,4) CHECK (VALUE > 0)`,
		`CREATE TABLE source_data.domain_items (id integer PRIMARY KEY, amount source_data.positive_amount NOT NULL)`,
		`INSERT INTO source_data.domain_items VALUES (1, 12.5000)`,
		`INSERT INTO source_data.items
         (name, payload, raw, tags, identifier, amount, duration, status, created_at)
         VALUES
         (E'line one\nline two\\tail', '{"enabled":true}', decode('00ff10','hex'),
          ARRAY['a','b'], '84b63d60-5733-4e52-a1ac-8c4e607a5011', 1234567890.1250,
          '2 days 03:04:05', 'ready', '2026-09-18T10:20:30Z')`,
		`INSERT INTO source_data.children (item_id, note) VALUES (1, E'child\ntext')`,
	)

	execStatements(t, ctx, targetAdmin,
		`DROP SCHEMA IF EXISTS target_data CASCADE`,
		`CREATE SCHEMA target_data`,
		`CREATE TYPE target_data.item_status AS ENUM ('new', 'ready')`,
		`CREATE SEQUENCE target_data.items_id_seq`,
		`CREATE SEQUENCE target_data.children_id_seq`,
		`CREATE TABLE target_data.items (
            id bigint PRIMARY KEY DEFAULT nextval('target_data.items_id_seq'),
            name text NOT NULL,
            payload jsonb,
            raw bytea,
            tags text[],
            identifier uuid,
            amount numeric(20,4),
            duration interval,
            status target_data.item_status,
            created_at timestamptz,
            display text GENERATED ALWAYS AS (name || ':' || id::text) STORED
        )`,
		`CREATE TABLE target_data.children (
            id bigint PRIMARY KEY DEFAULT nextval('target_data.children_id_seq'),
            item_id bigint NOT NULL REFERENCES target_data.items(id),
            note text NOT NULL
        )`,
		`INSERT INTO target_data.items (name) VALUES ('original')`,
		`INSERT INTO target_data.children (item_id, note) VALUES (1, 'original child')`,
		`CREATE FUNCTION target_data.reject_child_insert() RETURNS trigger
         LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'trigger should be disabled'; END $$`,
		`CREATE TRIGGER reject_child_insert BEFORE INSERT ON target_data.children
         FOR EACH ROW EXECUTE FUNCTION target_data.reject_child_insert()`,
	)

	sourceConfig := configFromDSN(t, sourceDSN, "source_data")
	targetConfig := configFromDSN(t, targetDSN, "target_data")
	source, err := OpenSource(ctx, sourceConfig, sourceConfig.Password, 1)
	if err != nil {
		t.Fatal(err)
	}
	defer source.Close(ctx)
	if _, err := source.conn.Exec(ctx, `INSERT INTO source_data.items (name) VALUES ('forbidden')`); err == nil {
		t.Fatal("source connection accepted a write")
	}
	target, err := OpenTarget(ctx, targetConfig)
	if err != nil {
		t.Fatal(err)
	}
	defer target.Close(ctx)

	dir := exportFixture(t, ctx, source, []string{"items", "children"})
	manifest, sequences, err := dump.Load(dir, true)
	if err != nil {
		t.Fatal(err)
	}
	selected := map[string]struct{}{"items": {}, "children": {}}
	schema, err := dump.LoadSchema(dir)
	if err != nil {
		t.Fatal(err)
	}
	if err := target.Restore(ctx, dir, manifest, sequences, selected, schema, nil, nil); err != nil {
		t.Fatal(err)
	}

	var name, display, payload, status, amount, duration string
	var raw []byte
	var tags []string
	err = targetAdmin.QueryRow(ctx, `
SELECT name, display, payload::text, raw, tags, status::text, amount::text, duration::text
FROM target_data.items`).Scan(&name, &display, &payload, &raw, &tags, &status, &amount, &duration)
	if err != nil {
		t.Fatal(err)
	}
	if name != "line one\nline two\\tail" || display != name+":1" || payload != `{"enabled": true}` ||
		fmt.Sprintf("%x", raw) != "00ff10" || len(tags) != 2 || status != "ready" ||
		amount != "1234567890.1250" || duration != "2 days 03:04:05" {
		t.Fatalf("unexpected restored item: name=%q display=%q payload=%q raw=%x tags=%v status=%q amount=%q duration=%q", name, display, payload, raw, tags, status, amount, duration)
	}
	var childNote string
	if err := targetAdmin.QueryRow(ctx, `SELECT note FROM target_data.children`).Scan(&childNote); err != nil {
		t.Fatal(err)
	}
	if childNote != "child\ntext" {
		t.Fatalf("child note = %q", childNote)
	}
	var next int64
	if err := targetAdmin.QueryRow(ctx, `SELECT nextval('target_data.items_id_seq')`).Scan(&next); err != nil {
		t.Fatal(err)
	}
	if next != 2 {
		t.Fatalf("next sequence value = %d, want 2", next)
	}

	// A malformed COPY stream must roll back all changes to selected tables.
	badDir, err := dump.CreateDir(t.TempDir(), time.Now())
	if err != nil {
		t.Fatal(err)
	}
	badRelative := filepath.Join("tables", "0001.copy.gz")
	badStats, err := dump.WriteCompressed(filepath.Join(badDir, badRelative), nil, func(writer io.Writer) error {
		_, err := io.WriteString(writer, "not-a-bigint\tbroken\n")
		return err
	})
	if err != nil {
		t.Fatal(err)
	}
	badManifest := manifest
	badManifest.Tables = append([]dump.Table(nil), manifest.Tables[0])
	badManifest.Tables[0].File = badRelative
	badManifest.Tables[0].CompressedBytes = badStats.CompressedBytes
	badManifest.Tables[0].UncompressedBytes = badStats.UncompressedBytes
	badManifest.Tables[0].SHA256 = badStats.SHA256
	if err := target.Restore(ctx, badDir, badManifest, nil, selected, schema, nil, nil); err == nil {
		t.Fatal("expected malformed COPY restore to fail")
	}
	var itemCount, childCount int
	if err := targetAdmin.QueryRow(ctx, `SELECT count(*) FROM target_data.items`).Scan(&itemCount); err != nil {
		t.Fatal(err)
	}
	if err := targetAdmin.QueryRow(ctx, `SELECT count(*) FROM target_data.children`).Scan(&childCount); err != nil {
		t.Fatal(err)
	}
	if itemCount != 1 || childCount != 1 {
		t.Fatalf("failed restore did not roll back truncation: items=%d children=%d", itemCount, childCount)
	}
	// A skipped child table must not be silently truncated through CASCADE.
	if err := target.Restore(ctx, dir, manifest, sequences, map[string]struct{}{"items": {}}, schema, nil, nil); err == nil {
		t.Fatal("expected foreign key to reject truncation with skipped child")
	}
	if err := targetAdmin.QueryRow(ctx, `SELECT count(*) FROM target_data.children`).Scan(&childCount); err != nil {
		t.Fatal(err)
	}
	if childCount != 1 {
		t.Fatalf("skipped child table changed: %d", childCount)
	}

	atomicConfig := targetConfig
	atomicConfig.Schema = "atomic_data"
	atomicTarget, err := OpenTarget(ctx, atomicConfig)
	if err != nil {
		t.Fatal(err)
	}
	defer atomicTarget.Close(ctx)
	if err := atomicTarget.Restore(ctx, badDir, badManifest, nil, map[string]struct{}{"items": {}}, schema, map[string]struct{}{"items": {}}, nil); err == nil {
		t.Fatal("expected malformed COPY to roll back new table creation")
	}
	var atomicSchemaExists bool
	if err := targetAdmin.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname='atomic_data')`).Scan(&atomicSchemaExists); err != nil {
		t.Fatal(err)
	}
	if atomicSchemaExists {
		t.Fatal("failed restore left a created schema behind")
	}

	// Rebuild an absent target schema using only metadata captured in the dump.
	execStatements(t, ctx, targetAdmin, `DROP SCHEMA target_data CASCADE`)
	if err := target.Restore(ctx, dir, manifest, sequences, selected, schema, selected, nil); err != nil {
		t.Fatalf("create missing tables from dump: %v", err)
	}
	var rebuilt, childRows int
	if err := targetAdmin.QueryRow(ctx, `SELECT count(*) FROM target_data.items`).Scan(&rebuilt); err != nil {
		t.Fatal(err)
	}
	if err := targetAdmin.QueryRow(ctx, `SELECT count(*) FROM target_data.children`).Scan(&childRows); err != nil {
		t.Fatal(err)
	}
	if rebuilt != 1 || childRows != 1 {
		t.Fatalf("rebuilt row counts: items=%d children=%d", rebuilt, childRows)
	}
	if err := targetAdmin.QueryRow(ctx, `SELECT nextval('target_data.items_id_seq')`).Scan(&next); err != nil {
		t.Fatal(err)
	}
	if next != 2 {
		t.Fatalf("rebuilt sequence next value = %d", next)
	}
	var indexPresent bool
	if err := targetAdmin.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM pg_catalog.pg_indexes WHERE schemaname='target_data' AND indexname='items_name_idx')`).Scan(&indexPresent); err != nil {
		t.Fatal(err)
	}
	if !indexPresent {
		t.Fatal("non-constraint index was not rebuilt")
	}
	identityDir := exportFixture(t, ctx, source, []string{"identity_items"})
	identityManifest, identitySequences, err := dump.Load(identityDir, true)
	if err != nil {
		t.Fatal(err)
	}
	identitySchema, err := dump.LoadSchema(identityDir)
	if err != nil {
		t.Fatal(err)
	}
	identitySelected := map[string]struct{}{"identity_items": {}}
	if err := target.Restore(ctx, identityDir, identityManifest, identitySequences, identitySelected, identitySchema, identitySelected, nil); err != nil {
		t.Fatalf("create identity table: %v", err)
	}
	var identityNext int64
	if err := targetAdmin.QueryRow(ctx, `SELECT nextval('target_data.identity_items_id_seq')`).Scan(&identityNext); err != nil {
		t.Fatal(err)
	}
	if identityNext != 12 {
		t.Fatalf("identity next value = %d, want 12", identityNext)
	}
	domainDir := exportFixture(t, ctx, source, []string{"domain_items"})
	domainManifest, domainSequences, err := dump.Load(domainDir, true)
	if err != nil {
		t.Fatal(err)
	}
	domainSchema, err := dump.LoadSchema(domainDir)
	if err != nil {
		t.Fatal(err)
	}
	domainSelected := map[string]struct{}{"domain_items": {}}
	if err := target.Restore(ctx, domainDir, domainManifest, domainSequences, domainSelected, domainSchema, domainSelected, nil); err != nil {
		t.Fatalf("create domain table: %v", err)
	}
	var domainAmount string
	if err := targetAdmin.QueryRow(ctx, `SELECT amount::text FROM target_data.domain_items`).Scan(&domainAmount); err != nil {
		t.Fatal(err)
	}
	if domainAmount != "12.5000" {
		t.Fatalf("domain amount = %q", domainAmount)
	}
}

func TestCreateMissingWithCustomTypeDependencies(t *testing.T) {
	if os.Getenv("PG_PULL_INTEGRATION") == "" {
		t.Skip("set PG_PULL_INTEGRATION=1 to run PostgreSQL integration tests")
	}
	ctx := context.Background()
	sourceDSN := testpostgres.DSN(t, "PG_PULL_TEST_SOURCE_DSN", "postgres:15-alpine")
	targetDSN := testpostgres.DSN(t, "PG_PULL_TEST_TARGET_DSN", "postgres:18-alpine")
	sourceAdmin := connectTestDB(t, ctx, sourceDSN)
	defer sourceAdmin.Close(ctx)
	targetAdmin := connectTestDB(t, ctx, targetDSN)
	defer targetAdmin.Close(ctx)

	execStatements(t, ctx, sourceAdmin,
		`DROP SCHEMA IF EXISTS source_data CASCADE`,
		`CREATE SCHEMA source_data`,
		`CREATE TYPE source_data.status AS ENUM ('new', 'ready')`,
		`CREATE DOMAIN source_data.status_domain AS source_data.status`,
		`CREATE DOMAIN source_data.status_chain AS source_data.status_domain`,
		`CREATE DOMAIN source_data.status_array_domain AS source_data.status_domain[]`,
		`CREATE TYPE source_data.unsupported_type AS (value text)`,
		`CREATE TABLE source_data.supported (
			id integer PRIMARY KEY,
			statuses source_data.status[],
			domain_statuses source_data.status_domain[],
			nested source_data.status_chain,
			domain_array source_data.status_array_domain
		)`,
		`CREATE INDEX "lookup ON name" ON source_data.supported (nested)`,
		`INSERT INTO source_data.supported VALUES
			(1, '{new,ready}', '{ready}', 'new', '{new}')`,
		`CREATE TABLE source_data.unsupported (id integer, value source_data.unsupported_type)`,
	)

	sourceConfig := configFromDSN(t, sourceDSN, "source_data")
	source, err := OpenSource(ctx, sourceConfig, sourceConfig.Password, 1)
	if err != nil {
		t.Fatal(err)
	}
	defer source.Close(ctx)
	dir := exportFixture(t, ctx, source, []string{"supported", "unsupported"})
	manifest, sequences, err := dump.Load(dir, true)
	if err != nil {
		t.Fatal(err)
	}
	schema, err := dump.LoadSchema(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, table := range schema.Tables {
		switch table.Name {
		case "supported":
			if len(table.Unsupported) != 0 {
				t.Fatalf("supported table marked unsupported: %v", table.Unsupported)
			}
		case "unsupported":
			if len(table.Unsupported) == 0 {
				t.Fatal("composite column was not marked unsupported")
			}
		}
	}

	targetConfig := configFromDSN(t, targetDSN, "types_target")
	target, err := OpenTarget(ctx, targetConfig)
	if err != nil {
		t.Fatal(err)
	}
	defer target.Close(ctx)
	execStatements(t, ctx, targetAdmin, `DROP SCHEMA IF EXISTS types_target CASCADE`)
	selected := map[string]struct{}{"supported": {}}
	if err := target.Restore(ctx, dir, manifest, sequences, selected, schema, selected, nil); err != nil {
		t.Fatalf("create supported table from mixed dump: %v", err)
	}
	var statuses, domainStatuses, nested, domainArray string
	err = targetAdmin.QueryRow(ctx, `SELECT statuses::text, domain_statuses::text,
		nested::text, domain_array::text FROM types_target.supported`).
		Scan(&statuses, &domainStatuses, &nested, &domainArray)
	if err != nil {
		t.Fatal(err)
	}
	if statuses != "{new,ready}" || domainStatuses != "{ready}" || nested != "new" || domainArray != "{new}" {
		t.Fatalf("restored custom types: statuses=%q domain_statuses=%q nested=%q domain_array=%q",
			statuses, domainStatuses, nested, domainArray)
	}
	var correct bool
	err = targetAdmin.QueryRow(ctx, `SELECT
		to_regtype('types_target.status') IS NOT NULL
		AND to_regtype('types_target.status_domain') IS NOT NULL
		AND to_regtype('types_target.status_chain') IS NOT NULL
		AND to_regtype('types_target.status_array_domain') IS NOT NULL
		AND to_regclass('types_target.unsupported') IS NULL
		AND EXISTS (SELECT 1 FROM pg_catalog.pg_indexes
			WHERE schemaname='types_target' AND indexname='lookup ON name')`).Scan(&correct)
	if err != nil {
		t.Fatal(err)
	}
	if !correct {
		t.Fatal("expected types or quoted index missing, or unsupported table was created")
	}
}

func TestParallelSnapshotsShareOneView(t *testing.T) {
	if os.Getenv("PG_PULL_INTEGRATION") == "" {
		t.Skip("set PG_PULL_INTEGRATION=1 to run PostgreSQL integration tests")
	}
	ctx := context.Background()
	sourceDSN := testpostgres.DSN(t, "PG_PULL_TEST_SOURCE_DSN", "postgres:15-alpine")
	admin := connectTestDB(t, ctx, sourceDSN)
	defer admin.Close(ctx)
	execStatements(t, ctx, admin,
		`DROP SCHEMA IF EXISTS parallel_data CASCADE`,
		`CREATE SCHEMA parallel_data`,
		`CREATE TABLE parallel_data.first (id bigint)`,
		`CREATE TABLE parallel_data.second (id bigint)`,
		`INSERT INTO parallel_data.first VALUES (1)`,
		`INSERT INTO parallel_data.second VALUES (1)`,
	)
	defer admin.Exec(context.Background(), `DROP SCHEMA IF EXISTS parallel_data CASCADE`) //nolint:errcheck
	settings := configFromDSN(t, sourceDSN, "parallel_data")
	source, err := OpenSource(ctx, settings, settings.Password, 2)
	if err != nil {
		t.Fatal(err)
	}
	defer source.Close(ctx)
	if source.Parallelism() != 2 {
		t.Fatalf("parallelism = %d", source.Parallelism())
	}
	if _, err := source.workers[0].Exec(ctx, `INSERT INTO parallel_data.first VALUES (9)`); err == nil {
		t.Fatal("source worker accepted a write")
	}
	coordinator, err := source.BeginSnapshot(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer coordinator.Rollback(ctx)
	id, err := coordinator.ExportID(ctx)
	if err != nil {
		t.Fatal(err)
	}
	// A later commit must be invisible to both COPY streams, even when they
	// run concurrently on separate connections.
	execStatements(t, ctx, admin,
		`INSERT INTO parallel_data.first VALUES (2)`,
		`INSERT INTO parallel_data.second VALUES (2)`,
	)
	worker, err := source.BeginImportedSnapshot(ctx, 0, id)
	if err != nil {
		t.Fatal(err)
	}
	defer worker.Rollback(ctx)
	var first, second bytes.Buffer
	var group sync.WaitGroup
	var firstErr, secondErr error
	group.Add(2)
	go func() {
		defer group.Done()
		_, firstErr = coordinator.CopyTable(ctx, "parallel_data", "first", []string{"id"}, &first)
	}()
	go func() {
		defer group.Done()
		_, secondErr = worker.CopyTable(ctx, "parallel_data", "second", []string{"id"}, &second)
	}()
	group.Wait()
	if firstErr != nil || secondErr != nil {
		t.Fatalf("parallel COPY errors: first=%v, second=%v", firstErr, secondErr)
	}
	if first.String() != "1\n" || second.String() != "1\n" {
		t.Fatalf("snapshot mismatch: first=%q, second=%q", first.String(), second.String())
	}
}

func exportFixture(t *testing.T, ctx context.Context, source *Source, tables []string) string {
	t.Helper()
	snapshot, err := source.BeginSnapshot(ctx)
	if err != nil {
		t.Fatal(err)
	}
	dir, err := dump.CreateDir(t.TempDir(), time.Now())
	if err != nil {
		t.Fatal(err)
	}
	manifest := dump.Manifest{CreatedAt: time.Now(), Source: "test", SourceSchema: "source_data"}
	refs, err := snapshot.SequenceRefs(ctx, "source_data", tables)
	if err != nil {
		t.Fatal(err)
	}
	schema, err := snapshot.CaptureSchema(ctx, "source_data", tables, refs)
	if err != nil {
		t.Fatal(err)
	}
	for index, tableName := range tables {
		columns, err := snapshot.Columns(ctx, "source_data", tableName)
		if err != nil {
			t.Fatal(err)
		}
		var names []string
		var manifestColumns []dump.Column
		for _, column := range columns {
			if !column.Generated {
				names = append(names, column.Name)
				manifestColumns = append(manifestColumns, dump.Column{Name: column.Name, Type: column.Type})
			}
		}
		relative := filepath.Join("tables", fmt.Sprintf("%04d.copy.gz", index+1))
		var rowCount int64
		stats, err := dump.WriteCompressed(filepath.Join(dir, relative), nil, func(writer io.Writer) error {
			var copyErr error
			rowCount, copyErr = snapshot.CopyTable(ctx, "source_data", tableName, names, writer)
			return copyErr
		})
		if err != nil {
			t.Fatal(err)
		}
		manifest.Tables = append(manifest.Tables, dump.Table{
			Name: tableName, File: relative, Columns: manifestColumns, RowCount: rowCount,
			CompressedBytes: stats.CompressedBytes, UncompressedBytes: stats.UncompressedBytes, SHA256: stats.SHA256,
		})
	}
	var sequences []dump.Sequence
	for _, ref := range refs {
		lastValue, isCalled, err := snapshot.SequenceState(ctx, "source_data", ref.Name)
		if err != nil {
			t.Fatal(err)
		}
		sequences = append(sequences, dump.Sequence{Name: ref.Name, LastValue: lastValue, IsCalled: isCalled})
	}
	if err := snapshot.Commit(ctx); err != nil {
		t.Fatal(err)
	}
	if err := dump.WriteSequences(dir, sequences); err != nil {
		t.Fatal(err)
	}
	if err := dump.WriteSchema(dir, schema); err != nil {
		t.Fatal(err)
	}
	if err := dump.WriteManifest(dir, manifest); err != nil {
		t.Fatal(err)
	}
	return dir
}

func connectTestDB(t *testing.T, ctx context.Context, dsn string) *pgx.Conn {
	t.Helper()
	conn, err := pgx.Connect(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	return conn
}

func execStatements(t *testing.T, ctx context.Context, conn *pgx.Conn, statements ...string) {
	t.Helper()
	for _, statement := range statements {
		if _, err := conn.Exec(ctx, statement); err != nil {
			t.Fatalf("setup %q: %v", statement, err)
		}
	}
}

func configFromDSN(t *testing.T, dsn, schema string) config.Database {
	t.Helper()
	parsed, err := pgx.ParseConfig(dsn)
	if err != nil {
		t.Fatal(err)
	}
	u, err := url.Parse(dsn)
	if err != nil {
		t.Fatal(err)
	}
	return config.Database{
		Host: parsed.Host, Port: parsed.Port, DBName: parsed.Database, User: parsed.User,
		Password: parsed.Password, Schema: schema, SSLMode: u.Query().Get("sslmode"),
	}
}
